FROM python:3.9-slim
RUN pip install mlflow psycopg2-binary
EXPOSE 5001
CMD chmod -R 777 ${MLFLOW_ARTIFACT_ROOT} && mlflow server --host 0.0.0.0 --port 5001 --backend-store-uri ${MLFLOW_BACKEND_STORE_URI} --default-artifact-root ${MLFLOW_ARTIFACT_ROOT}
